# Standalone Home Manager output for occhima (non-NixOS machines),
# generated by Den from the same `occhima` user aspect. The pkgs override
# keeps the unfree/overlay behavior of the previous output; no fabricated
# osConfig — modules take `osConfig ? { }` and degrade intentionally.
{ config, inputs, ... }:
{
  den.homes.x86_64-linux.occhima = {
    pkgs = import inputs.nixpkgs {
      system = "x86_64-linux";
      config = config.flake.lib.custom.nixpkgsConfig;
      overlays = builtins.attrValues config.flake.overlays;
    };
  };
}
