#+TITLE: Home Manager Configurations
#+AUTHOR: occhima
#+DESCRIPTION: User-specific Home Manager configurations

* Overview

This directory contains user-specific Home Manager configurations. Each user has their own directory with user-specific settings, while leveraging shared modules from the ~modules/home-manager/~ directory.

* Directory Structure

- ~flake-module.nix~ - Exports all user configurations as homeConfigurations
- ~<username>/~ - User-specific Home Manager configuration
  - ~default.nix~ - Main user configuration

* Users

** occhima

Primary user configuration with comprehensive shell, desktop, and tools setup.

* Home Manager Integration

Home Manager is used in two ways in this configuration:

1. *Standalone mode* - For users on non-NixOS systems (via this directory)
2. *NixOS module mode* - For users on NixOS systems (via modules/nixos/accounts)

The configurations in this directory are used in both cases.

* Home Configuration Structure

A typical user configuration looks like this:

#+begin_src nix
{ config, ... }:
{
  home = {
    username = "username";
    homeDirectory = "/home/${config.home.username}";
  };

  # Enable modules
  modules = {
    shell = {
      type = "zsh";
      prompt.type = "starship";
    };

    data = {
      xdg.enable = true;
      persistence.enable = true;
    };

    # Other module configurations...
  };
}
#+end_src

* Adding a New User

To add a new user:

1. Create a new directory for the user: ~home/newuser/~
2. Add a ~default.nix~ file with the user's Home Manager configuration
3. Create a system user definition in ~modules/nixos/accounts/users/newuser.nix~
4. Add the user to ~allUsers~ in ~modules/nixos/accounts/accounts.nix~
5. Enable the user in your host configuration

For standalone usage (outside of NixOS), the user will be automatically added to the flake outputs via ~homeConfigurations~.

* Using Home Manager Independently

To apply a user's Home Manager configuration independently:

#+begin_src bash
home-manager switch --flake .#username@hostname
#+end_src

Or using the convenience command:

#+begin_src bash
just home-switch hostname
#+end_src

* Further Reading

For detailed information on adding and configuring users, see:
- [[../docs/guides/adding-user.md][Adding a New User Guide]]
- [[../docs/modules/home-manager/index.md][Home Manager Modules Documentation]]
