;;; core-keybinds.el --- Centralized keymaps -*- lexical-binding: t; -*-

(require 'core-evil)
(require 'core-commands)

(occhima/leader
  "TAB" '(:prefix-command occhima/workspace-map :wk "workspace")
  "b" '(:prefix-command occhima/buffer-map :wk "buffer")
  "c" '(:prefix-command occhima/code-map :wk "code")
  "f" '(:prefix-command occhima/file-map :wk "file")
  "g" '(:prefix-command occhima/git-map :wk "git")
  "i" '(:prefix-command occhima/insert-map :wk "insert")
  "j" '(:prefix-command occhima/just-map :wk "just")
  "n" '(:prefix-command occhima/notes-map :wk "notes")
  "nr" '(:prefix-command occhima/roam-map :wk "roam")
  "O" '(:prefix-command occhima/agent-map :wk "opencode")
  "o" '(:prefix-command occhima/open-map :wk "open")
  "oa" '(:prefix-command occhima/agenda-map :wk "org agenda")
  "C" '(claude-code-transient-menu :wk "Claude Code")
  "p" '(:prefix-command occhima/project-map :wk "project")
  "q" '(:prefix-command occhima/quit-map :wk "quit/session")
  "s" '(:prefix-command occhima/search-map :wk "search")
  "t" '(:prefix-command occhima/toggle-map :wk "toggle")

  ";" '(pp-eval-expression :wk "Eval expression")
  ":" '(execute-extended-command :wk "M-x")
  "x" '(occhima/open-scratch-buffer :wk "Pop up scratch buffer")
  "X" '(org-capture :wk "Org capture")
  "u" '(universal-argument :wk "Universal argument")
  "w" '(:keymap evil-window-map :wk "window")
  "h" '(:keymap help-map :wk "help")
  "." '(find-file :wk "Find file")
  "," '(occhima/workspace-buffer :wk "Switch workspace buffer")
  "<" '(consult-buffer :wk "Switch buffer")
  "*" '(occhima/search-project-for-symbol-at-point :wk "Search project for symbol")
  "`" '(occhima/switch-to-last-buffer :wk "Last buffer")
  "'" '(vertico-repeat :wk "Resume search")
  "/" '(consult-ripgrep :wk "Search project")
  "SPC" '(project-find-file :wk "Find project file")
  "RET" '(bookmark-jump :wk "Jump to bookmark")

  "TAB TAB" '(tab-bar-switch-to-tab :wk "Switch workspace")
  "TAB `" '(tab-recent :wk "Last workspace")
  "TAB [" '(tab-previous :wk "Previous workspace")
  "TAB ]" '(tab-next :wk "Next workspace")
  "TAB d" '(tab-close :wk "Delete workspace")
  "TAB n" '(tab-new :wk "New workspace")
  "TAB r" '(tab-rename :wk "Rename workspace")
  "TAB N" '(occhima/workspace-new-named :wk "New named workspace")
  "TAB 0" '(tab-last :wk "Final workspace")
  "TAB ." '(tab-switch :wk "Switch workspace")
  "TAB x" '(occhima/workspace-kill-session :wk "Kill other workspaces")
  "TAB X" '(tab-close-group :wk "Close workspace group")

  "b [" '(previous-buffer :wk "Previous buffer")
  "b ]" '(next-buffer :wk "Next buffer")
  "b -" '(occhima/toggle-narrow-buffer :wk "Toggle narrowing")
  "b b" '(occhima/workspace-buffer :wk "Switch workspace buffer")
  "b B" '(consult-buffer :wk "Switch buffer")
  "b I" '(ibuffer :wk "Ibuffer")
  "b K" '(occhima/kill-all-buffers :wk "Kill all buffers")
  "b u" '(occhima/sudo-save-buffer :wk "Save buffer as root")
  "b X" '(occhima/switch-to-scratch-buffer :wk "Switch to scratch buffer")
  "b Z" '(occhima/kill-buried-buffers :wk "Kill buried buffers")
  "b c" '(clone-indirect-buffer :wk "Clone buffer")
  "b C" '(clone-indirect-buffer-other-window :wk "Clone in other window")
  "b d" '(kill-current-buffer :wk "Kill buffer")
  "b i" '(ibuffer :wk "Ibuffer")
  "b k" '(kill-current-buffer :wk "Kill buffer")
  "b l" '(occhima/switch-to-last-buffer :wk "Last buffer")
  "b m" '(bookmark-set :wk "Set bookmark")
  "b M" '(bookmark-delete :wk "Delete bookmark")
  "b n" '(next-buffer :wk "Next buffer")
  "b N" '(occhima/new-empty-buffer :wk "New buffer")
  "b O" '(occhima/kill-other-buffers :wk "Kill other buffers")
  "b p" '(previous-buffer :wk "Previous buffer")
  "b r" '(revert-buffer :wk "Revert buffer")
  "b R" '(rename-buffer :wk "Rename buffer")
  "b s" '(basic-save-buffer :wk "Save buffer")
  "b S" '(evil-write-all :wk "Save all buffers")
  "b x" '(occhima/open-scratch-buffer :wk "Pop up scratch buffer")
  "b y" '(occhima/copy-buffer-contents :wk "Yank buffer")
  "b z" '(bury-buffer :wk "Bury buffer")

  "c a" '(eglot-code-actions :wk "Code action")
  "c c" '(compile :wk "Compile")
  "c C" '(recompile :wk "Recompile")
  "c f" '(apheleia-format-buffer :wk "Format buffer")
  "c d" '(xref-find-definitions :wk "Definition")
  "c D" '(xref-find-references :wk "References")
  "c e" '(occhima/eval-dwim :wk "Evaluate buffer/region")
  "c E" '(occhima/eval-and-replace :wk "Evaluate & replace region")
  "c i" '(eglot-find-implementation :wk "Implementations")
  "c j" '(consult-eglot-symbols :wk "Jump to workspace symbol")
  "c o" '(eglot-code-action-organize-imports :wk "Organize imports")
  "c s" '(occhima/eval-dwim :wk "Send to REPL")
  "c t" '(eglot-find-typeDefinition :wk "Type definition")
  "c W" '(occhima/delete-trailing-newlines :wk "Delete trailing newlines")
  "c k" '(eldoc-doc-buffer :wk "Documentation")
  "c r" '(eglot-rename :wk "Rename symbol")
  "c w" '(delete-trailing-whitespace :wk "Delete trailing whitespace")
  "c x" '(consult-flymake :wk "Diagnostics")

  "f c" '(editorconfig-find-current-editorconfig :wk "Open editorconfig")
  "f C" '(occhima/copy-this-file :wk "Copy this file")
  "f d" '(dired :wk "Find directory")
  "f D" '(occhima/delete-this-file :wk "Delete this file")
  "f E" '(occhima/browse-emacs-directory :wk "Browse emacs.d")
  "f F" '(occhima/find-file-under-here :wk "Find file from here")
  "f p" '(occhima/find-file-in-config :wk "Find file in private config")
  "f P" '(occhima/browse-config :wk "Browse private config")
  "f R" '(rename-visited-file :wk "Rename/move file")
  "f u" '(occhima/sudo-find-file :wk "Sudo find file")
  "f U" '(occhima/sudo-this-file :wk "Sudo this file")
  "f e" '(occhima/find-file-in-config :wk "Find in config")
  "f f" '(find-file :wk "Find file")
  "f l" '(locate :wk "Locate file")
  "f r" '(recentf-open-files :wk "Recent files")
  "f s" '(basic-save-buffer :wk "Save file")
  "f S" '(write-file :wk "Save file as")
  "f y" '(occhima/copy-buffer-path :wk "Yank file path")
  "f Y" '(occhima/copy-buffer-path-relative-to-project
          :wk "Yank project-relative path")

  "i e" '(emoji-search :wk "Emoji")
  "i f" '(occhima/insert-file-path :wk "Current file name")
  "i F" '(occhima/insert-file-full-path :wk "Current file path")
  "i p" '(occhima/insert-shell-output :wk "Evil ex path")
  "i s" '(tempel-insert :wk "Snippet")
  "i y" '(consult-yank-pop :wk "From clipboard")
  "i r" '(evil-show-registers :wk "Register")
  "i u" '(insert-char :wk "Unicode")

  "n a" '(org-agenda :wk "Org agenda")
  "n b" '(citar-open-notes :wk "Bibliographic notes")
  "n c" '(org-clock-in-last :wk "Clock in last")
  "n C" '(org-clock-cancel :wk "Cancel clock")
  "n e" '(org-noter :wk "Org noter")
  "n f" '(occhima/find-in-notes :wk "Find file in notes")
  "n F" '(occhima/browse-notes :wk "Browse notes")
  "n o" '(org-clock-goto :wk "Active clock")
  "n S" '(consult-org-agenda :wk "Search agenda headlines")
  "n l" '(org-store-link :wk "Store link")
  "n m" '(org-tags-view :wk "Tags search")
  "n n" '(org-capture :wk "Org capture")
  "n N" '(org-capture-goto-target :wk "Goto capture")
  "n *" '(occhima/search-notes-for-symbol-at-point :wk "Search notes for symbol")
  "n s" '(occhima/search-notes :wk "Search notes")
  "n t" '(org-todo-list :wk "Todo list")
  "n v" '(org-search-view :wk "View search")
  "nr a" '(org-roam-node-random :wk "Random node")
  "nr f" '(org-roam-node-find :wk "Find node")
  "nr F" '(org-roam-ref-find :wk "Find reference")
  "nr g" '(org-roam-graph :wk "Show graph")
  "nr i" '(org-roam-node-insert :wk "Insert node")
  "nr n" '(org-roam-capture :wk "Capture node")
  "nr r" '(org-roam-buffer-toggle :wk "Toggle roam buffer")
  "nr s" '(org-roam-db-sync :wk "Sync database")
  "nr R" '(org-roam-buffer-display-dedicated :wk "Launch roam buffer")
  "nr d b" '(org-roam-dailies-goto-previous-note :wk "Previous note")
  "nr d d" '(org-roam-dailies-goto-date :wk "Goto date")
  "nr d D" '(org-roam-dailies-capture-date :wk "Capture date")
  "nr d f" '(org-roam-dailies-goto-next-note :wk "Next note")
  "nr d m" '(org-roam-dailies-goto-tomorrow :wk "Goto tomorrow")
  "nr d M" '(org-roam-dailies-capture-tomorrow :wk "Capture tomorrow")
  "nr d n" '(org-roam-dailies-capture-today :wk "Capture today")
  "nr d t" '(org-roam-dailies-goto-today :wk "Goto today")
  "nr d y" '(org-roam-dailies-goto-yesterday :wk "Goto yesterday")
  "nr d Y" '(org-roam-dailies-capture-yesterday :wk "Capture yesterday")

  "o A" '(org-agenda :wk "Org agenda")
  "o a a" '(org-agenda :wk "Agenda")
  "o a m" '(org-tags-view :wk "Tags search")
  "o a t" '(org-todo-list :wk "Todo list")
  "o a o" '(occhima/open-agenda :wk "Personal agenda")
  "o a v" '(org-search-view :wk "View search")
  "o b" '(browse-url-of-file :wk "Default browser")
  "o c" '(calendar :wk "Calendar")
  "o f" '(make-frame :wk "New frame")
  "o F" '(select-frame-by-name :wk "Select frame")
  "o -" '(dired-jump :wk "Dired")
  "o /" '(dirvish :wk "Dirvish")
  "o p" '(dirvish-side :wk "Project sidebar")
  "o P" '(dirvish-side :wk "Find file in project sidebar")
  "o r" '(occhima/open-repl :wk "REPL")
  "o R" '(occhima/open-repl-same-window :wk "REPL (same window)")

  "p ." '(project-dired :wk "Browse project")
  "p >" '(occhima/browse-other-project :wk "Browse other project")
  "p i" '(project-forget-zombie-projects :wk "Forget missing projects")
  "p x" '(occhima/pop-project-scratch-buffer :wk "Pop up project scratch")
  "p X" '(occhima/switch-to-project-scratch-buffer :wk "Switch to project scratch")
  "p b" '(consult-project-buffer :wk "Project buffer")
  "p c" '(project-compile :wk "Compile project")
  "p d" '(project-forget-project :wk "Forget project")
  "p f" '(project-find-file :wk "Find project file")
  "p k" '(project-kill-buffers :wk "Kill project buffers")
  "p p" '(project-switch-project :wk "Switch project")
  "p s" '(occhima/save-project-buffers :wk "Save project buffers")

  "s b" '(consult-line :wk "Search buffer")
  "s B" '(consult-line-multi :wk "Search open buffers")
  "s d" '(occhima/search-cwd :wk "Search current directory")
  "s D" '(occhima/search-other-cwd :wk "Search other directory")
  "s e" '(occhima/search-config :wk "Search config")
  "s k" '(devdocs-lookup :wk "Look up in docs")
  "s K" '(devdocs-search :wk "Search all docs")
  "s l" '(link-hint-open-link :wk "Jump to visible link")
  "s L" '(ffap-menu :wk "Jump to link")
  "s O" '(occhima/lookup-online-select :wk "Look up online (w/ prompt)")
  "s P" '(occhima/search-other-project :wk "Search other project")
  "s S" '(occhima/search-buffer-for-symbol-at-point :wk "Search buffer for symbol")
  "s t" '(dictionary-lookup-definition :wk "Dictionary")
  "s T" '(powerthesaurus-lookup-synonyms-dwim :wk "Thesaurus")
  "s f" '(locate :wk "Locate file")
  "s g" '(consult-gh-search-repos :wk "Search GitHub repos")
  "s i" '(consult-imenu :wk "Jump to symbol")
  "s I" '(consult-imenu-multi :wk "Symbols in open buffers")
  "s j" '(evil-show-jumps :wk "Jump list")
  "s m" '(bookmark-jump :wk "Bookmark")
  "s o" '(consult-omni-multi :wk "Omni search")
  "s p" '(consult-ripgrep :wk "Search project")
  "s r" '(evil-show-marks :wk "Jump to mark")
  "s s" '(consult-line :wk "Search buffer")

  "t b" '(occhima/big-font-mode :wk "Big mode")
  "t c" '(global-display-fill-column-indicator-mode :wk "Fill column")
  "t g" '(goggles-mode :wk "Goggles")
  "t i" '(indent-bars-mode :wk "Indent guides")
  "t I" '(occhima/toggle-indent-style :wk "Indent style")
  "t f" '(flymake-mode :wk "Flymake")
  "t F" '(toggle-frame-fullscreen :wk "Fullscreen")
  "t l" '(display-line-numbers-mode :wk "Line numbers")
  "t r" '(read-only-mode :wk "Read-only")
  "t s" '(jinx-mode :wk "Spell checker")
  "t v" '(visible-mode :wk "Visible mode")
  "t w" '(visual-line-mode :wk "Soft wrapping"))

(dotimes (index 9)
  (let ((number (1+ index)))
    (general-define-key
     :keymaps 'occhima/leader-map
     (format "TAB %d" number)
     `(,(lambda () (interactive) (tab-bar-select-tab number))
       :wk ,(format "Workspace %d" number)))))

(occhima/leader
  "q d" '(occhima/restart-server :wk "Restart emacs server")
  "q F" '(occhima/kill-all-buffers :wk "Clear current frame")
  "q Q" '(evil-quit-all-with-error-code :wk "Quit without saving")
  "q r" '(restart-emacs :wk "Restart Emacs")
  "q s" '(occhima/session-save :wk "Quick save session")
  "q l" '(occhima/session-load :wk "Restore last session")
  "q S" '(occhima/session-save-to :wk "Save session to file")
  "q L" '(occhima/session-load-from :wk "Restore session from file"))

(general-def
  :keymaps 'evil-window-map
  "C-h" #'evil-window-left
  "C-j" #'evil-window-down
  "C-k" #'evil-window-up
  "C-l" #'evil-window-right
  "C-w" #'other-window
  "S" #'occhima/window-split-and-follow
  "V" #'occhima/window-vsplit-and-follow
  "H" #'windmove-swap-states-left
  "J" #'windmove-swap-states-down
  "K" #'windmove-swap-states-up
  "L" #'windmove-swap-states-right
  "m m" #'occhima/window-maximize-buffer
  "u" #'winner-undo
  "C-u" #'winner-undo
  "C-r" #'winner-redo
  "o" #'maximize-window
  "d" #'evil-window-delete
  "T" #'tear-off-window)

(keymap-set occhima/leader-map "m"
            '(menu-item "localleader" nil
                        :filter occhima/current-local-leader-map))

(provide 'core-keybinds)
;;; core-keybinds.el ends here
