{
  imports = [
    ./anyrun.nix
    ./emacs.nix
    ./ghostty.nix
    ./gtk.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./kitty.nix
    ./mako.nix
    ./niri.nix
    ./nixvim.nix
    ./nyxt.nix
    ./rofi.nix
    ./quickshell.nix
    ./schizofox.nix
    ./spicetify.nix
    ./vscode.nix
    ./waybar
    ./wlogout.nix
    ./zellij.nix
    ./zen.nix
  ];
}
