{ inputs, ... }:
{
  imports = [ inputs.treefmt-nix.flakeModule ];
  perSystem =
    { pkgs, config, ... }:
    {
      formatter = config.treefmt.programs.nixfmt.package;
      treefmt = {

        # enabled to be the base formatter
        flakeFormatter = true;

        # pre commit already makes this check
        flakeCheck = true;
        projectRootFile = "flake.nix";

        # flake.nix is generated by flake-file (write-flake) and its
        # up-to-date check diffs against flake-file's own nixfmt output;
        # reformatting it with nixfmt-rfc-style makes the two disagree.
        settings.global.excludes = [ "flake.nix" ];

        programs = {
          # Nix
          nixfmt = {
            enable = true;
            package = pkgs.nixfmt-classic;
          };

          alejandra = {
            enable = false;
          };

          # QML
          # qmlformat = {
          #   enable = true;
          # };

          deadnix = {
            enable = true;
          };

          # Github Actions
          actionlint = {
            enable = true;
          };

          # Bash
          beautysh = {
            enable = true;
          };

          # TypeScript / JSON
          # biome = { enable = true; };

          # Lua
          stylua = {
            enable = true;
          };

          # YAML
          prettier = {
            enable = true;
          };
        };

      };
    };
}
