jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - env:
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
      name: GitGuardian scan
      uses: GitGuardian/ggshield/actions/secret@v1.38.1
    timeout-minutes: 120
name: Flake Check
'on':
  push: {}
